name: Node CI


on:
  - push
  - pull_request

jobs:
  eslint:

    
    runs-on: ubuntu-latest
        
    steps:
        
        
      - uses: actions/checkout@v1
        
      - name: npm install
        
        run: |
          make install
      - name: run linter
        
        run: |
          make lint
